name: 'Setup Action'
description: 'Checkouts the repo, sets up node, and installs dependencies'
runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

    - name: Install pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
      with:
        version: '10.24.0'
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
      with:
        node-version: 22
        cache: 'pnpm'

    - name: Install dependencies
      run: 'pnpm install --frozen-lockfile'
      shell: bash
