name: 'Setup Action'
description: 'Sets up node and installs dependencies (assumes repo is already checked out)'
runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
      with:
        version: '10.30.0'
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
      with:
        node-version: 24
        cache: 'pnpm'

    - name: Install dependencies
      run: 'pnpm install --frozen-lockfile'
      shell: bash
