name: 'Setup Action'
description: 'Checkouts the repo, sets up node, and installs dependencies'
runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

    - name: Install pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
      with:
        version: '10.24.0'
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
      with:
        node-version: 24
        cache: 'pnpm'

    - name: Install dependencies
      run: 'pnpm install --frozen-lockfile'
      shell: bash
