name: 'Setup Action'
description: 'Sets up node and installs dependencies (assumes repo is already checked out)'
runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4
      with:
        version: '10.32.1'
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
      with:
        node-version: 24
        cache: 'pnpm'

    - name: Install dependencies
      run: 'pnpm install --frozen-lockfile'
      shell: bash
