name: 'Setup Action'
description: 'Checkouts the repo, sets up node, and installs dependencies'
runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

    - name: Install pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
      with:
        version: '10.11.0'
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: 22
        cache: 'pnpm'

    - name: Install dependencies
      run: 'pnpm install --frozen-lockfile'
      shell: bash
