import { customHandlers } from './customHandlers'
import { autoGeneratedHandlers } from './mocker'

// Register custom handlers first so they take precedence; auto-generated
// handlers act as fallbacks only when no custom handler matches.
export const handlers = [...customHandlers, ...autoGeneratedHandlers]
