import { customHandlers } from './customHandlers'
import { autoGeneratedHandlers } from './mocker'

export const handlers = [
  ...customHandlers,

  // fallback/default handlers
  ...autoGeneratedHandlers,
]
