import { customHandlers } from './customHandlers'
import { autoGeneratedHandlers } from './mocker'

// Register auto-generated fallbacks first, then custom handlers last so
// that custom handlers take precedence when MSW searches from the end.
export const handlers = [
  // fallback/default handlers
  ...autoGeneratedHandlers,
  // custom overrides
  ...customHandlers,
]
