/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as StoreImport } from "./routes/store";
import { Route as IndexImport } from "./routes/index";
import { Route as ServerServerNameImport } from "./routes/server/$serverName";

// Create/Update Routes

const StoreRoute = StoreImport.update({
  id: "/store",
  path: "/store",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const ServerServerNameRoute = ServerServerNameImport.update({
  id: "/server/$serverName",
  path: "/server/$serverName",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/store": {
      id: "/store";
      path: "/store";
      fullPath: "/store";
      preLoaderRoute: typeof StoreImport;
      parentRoute: typeof rootRoute;
    };
    "/server/$serverName": {
      id: "/server/$serverName";
      path: "/server/$serverName";
      fullPath: "/server/$serverName";
      preLoaderRoute: typeof ServerServerNameImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/store": typeof StoreRoute;
  "/server/$serverName": typeof ServerServerNameRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/store": typeof StoreRoute;
  "/server/$serverName": typeof ServerServerNameRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/store": typeof StoreRoute;
  "/server/$serverName": typeof ServerServerNameRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/store" | "/server/$serverName";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/store" | "/server/$serverName";
  id: "__root__" | "/" | "/store" | "/server/$serverName";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  StoreRoute: typeof StoreRoute;
  ServerServerNameRoute: typeof ServerServerNameRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StoreRoute: StoreRoute,
  ServerServerNameRoute: ServerServerNameRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/store",
        "/server/$serverName"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/store": {
      "filePath": "store.tsx"
    },
    "/server/$serverName": {
      "filePath": "server/$serverName.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
