/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as RegistryImport } from "./routes/registry";
import { Route as IndexImport } from "./routes/index";

// Create/Update Routes

const RegistryRoute = RegistryImport.update({
  id: "/registry",
  path: "/registry",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/registry": {
      id: "/registry";
      path: "/registry";
      fullPath: "/registry";
      preLoaderRoute: typeof RegistryImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/registry": typeof RegistryRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/registry": typeof RegistryRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/registry": typeof RegistryRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/registry";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/registry";
  id: "__root__" | "/" | "/registry";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  RegistryRoute: typeof RegistryRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegistryRoute: RegistryRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/registry"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/registry": {
      "filePath": "registry.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
