export type McpRegistryItem = (typeof MCP_REGISTRY)[number];

export const MCP_REGISTRY = [
  {
    name: "atlassian",
    image: "mcp/atlassian:latest",
    description:
      "Model Context Protocol (MCP) server for Atlassian products (Confluence and Jira). This integration supports both Confluence \u0026 Jira Cloud and Server/Data Center deployments.",
    transport: "stdio",
    permissions: {
      network: {
        outbound: {
          allow_transport: ["tcp"],
          allow_host: ["atlassian.net", "atlassian.com"],
          allow_port: [443],
        },
      },
    },
    tools: [
      "confluence_search",
      "confluence_get_page",
      "confluence_get_page_children",
      "confluence_get_page_ancestors",
      "confluence_get_comments",
      "confluence_create_page",
      "confluence_update_page",
      "confluence_delete_page",
      "confluence_attach_content",
      "jira_get_issue",
      "jira_search",
      "jira_get_project_issues",
      "jira_get_epic_issues",
      "jira_create_issue",
      "jira_update_issue",
      "jira_delete_issue",
      "jira_get_transitions",
      "jira_transition_issue",
      "jira_add_comment",
      "jira_add_worklog",
      "jira_get_worklog",
      "jira_download_attachments",
      "jira_link_to_epic",
      "jira_get_agile_boards",
      "jira_get_board_issues",
      "jira_get_sprints_from_board",
      "jira_get_sprint_issues",
    ],
    env_vars: [
      {
        name: "CONFLUENCE_URL",
        description:
          "Confluence URL (e.g., https://your-domain.atlassian.net/wiki)",
        required: false,
      },
      {
        name: "CONFLUENCE_USERNAME",
        description: "Confluence username/email for Cloud deployments",
        required: false,
      },
      {
        name: "CONFLUENCE_API_TOKEN",
        description: "Confluence API token for Cloud deployments",
        required: false,
      },
      {
        name: "CONFLUENCE_PERSONAL_TOKEN",
        description:
          "Confluence Personal Access Token for Server/Data Center deployments",
        required: false,
      },
      {
        name: "CONFLUENCE_SSL_VERIFY",
        description:
          "Verify SSL certificates for Confluence Server/Data Center (true/false)",
        required: false,
      },
      {
        name: "CONFLUENCE_SPACES_FILTER",
        description:
          "Comma-separated list of Confluence space keys to filter search results",
        required: false,
      },
      {
        name: "JIRA_URL",
        description: "Jira URL (e.g., https://your-domain.atlassian.net)",
        required: false,
      },
      {
        name: "JIRA_USERNAME",
        description: "Jira username/email for Cloud deployments",
        required: false,
      },
      {
        name: "JIRA_API_TOKEN",
        description: "Jira API token for Cloud deployments",
        required: false,
      },
      {
        name: "JIRA_PERSONAL_TOKEN",
        description:
          "Jira Personal Access Token for Server/Data Center deployments",
        required: false,
      },
      {
        name: "JIRA_SSL_VERIFY",
        description:
          "Verify SSL certificates for Jira Server/Data Center (true/false)",
        required: false,
      },
      {
        name: "JIRA_PROJECTS_FILTER",
        description:
          "Comma-separated list of Jira project keys to filter search results",
        required: false,
      },
      {
        name: "READ_ONLY_MODE",
        description: "Run in read-only mode (disables all write operations)",
        required: false,
      },
      {
        name: "MCP_VERBOSE",
        description: "Increase logging verbosity",
        required: false,
      },
    ],
    args: [],
    metadata: {
      stars: 1662,
      pulls: 4489,
      last_updated: "2025-05-27T00:20:44Z",
    },
    repository_url: "https://github.com/sooperset/mcp-atlassian",
    tags: [
      "atlassian",
      "confluence",
      "jira",
      "wiki",
      "issue-tracking",
      "project-management",
      "documentation",
      "cloud",
      "server",
      "data-center",
    ],
  },
  {
    name: "aws-kb-retrieval-server",
    image: "mcp/aws-kb-retrieval-server:latest",
    description:
      "MCP server for retrieving information from the AWS Knowledge Base using the Bedrock Agent Runtime.",
    transport: "stdio",
    permissions: {
      network: {
        outbound: {
          insecure_allow_all: true,
          allow_transport: ["tcp"],
          allow_port: [443],
        },
      },
    },
    tools: ["retrieve_from_aws_kb"],
    env_vars: [
      {
        name: "AWS_ACCESS_KEY_ID",
        description: "AWS access key ID for Bedrock Agent Runtime operations",
        required: true,
      },
      {
        name: "AWS_SECRET_ACCESS_KEY",
        description:
          "AWS secret access key for Bedrock Agent Runtime operations",
        required: true,
      },
      {
        name: "AWS_REGION",
        description: "AWS region where the Knowledge Base is located",
        required: true,
      },
    ],
    args: [],
    metadata: {
      stars: 49139,
      pulls: 2657,
      last_updated: "2025-05-27T00:20:45Z",
    },
    repository_url: "https://github.com/modelcontextprotocol/servers",
    tags: [
      "agent",
      "aws",
      "aws-kb-retrieval-server",
      "base",
      "bedrock",
      "information",
      "knowledge",
      "retrieval",
      "retrieving",
      "runtime",
    ],
  },
  {
    name: "brave-search",
    image: "mcp/brave-search:latest",
    description:
      "MCP server that integrates the Brave Search API, providing both web and local search capabilities.",
    transport: "stdio",
    permissions: {
      network: {
        outbound: {
          allow_transport: ["tcp"],
          allow_host: ["brave.com", "api.search.brave.com"],
          allow_port: [443],
        },
      },
    },
    tools: ["brave_web_search", "brave_local_search"],
    env_vars: [
      {
        name: "BRAVE_API_KEY",
        description:
          "Brave Search API key for web and local search capabilities",
        required: true,
      },
    ],
    args: [],
    metadata: {
      stars: 49139,
      pulls: 6393,
      last_updated: "2025-05-27T00:20:42Z",
    },
    repository_url: "https://github.com/modelcontextprotocol/servers",
    tags: [
      "api",
      "both",
      "brave",
      "brave-search",
      "brave_local_search",
      "capabilities",
      "execute",
      "integrates",
      "local",
      "providing",
    ],
  },
  {
    name: "everart",
    image: "mcp/everart:latest",
    description:
      "Image generation server for Claude Desktop using EverArt's API.",
    transport: "stdio",
    permissions: {
      network: {
        outbound: {
          allow_transport: ["tcp"],
          allow_port: [443],
        },
      },
    },
    tools: ["generate_image"],
    env_vars: [
      {
        name: "EVERART_API_KEY",
        description: "EverArt API key for image generation",
        required: true,
      },
    ],
    args: [],
    metadata: {
      stars: 49139,
      pulls: 4714,
      last_updated: "2025-05-27T00:20:44Z",
    },
    repository_url: "https://github.com/modelcontextprotocol/servers",
    tags: [
      "api",
      "claude",
      "desktop",
      "everart",
      "generation",
      "image",
      "tools",
      "using",
    ],
  },
  {
    name: "everything",
    image: "mcp/everything:latest",
    description:
      "This MCP server attempts to exercise all the features of the MCP protocol",
    transport: "stdio",
    permissions: {
      network: {
        outbound: {
          allow_transport: ["tcp"],
          allow_port: [443],
        },
      },
    },
    tools: [
      "echo",
      "add",
      "longRunningOperation",
      "sampleLLM",
      "getTinyImage",
      "printEnv",
      "annotatedMessage",
    ],
    env_vars: [],
    args: [],
    metadata: {
      stars: 49139,
      pulls: 6151,
      last_updated: "2025-05-27T00:20:43Z",
    },
    repository_url: "https://github.com/modelcontextprotocol/servers",
    tags: [
      "adds",
      "all",
      "attempts",
      "demonstrates",
      "everything",
      "exercise",
      "features",
      "returns",
      "simple",
      "tools",
    ],
  },
  {
    name: "fetch",
    image: "mcp/fetch:latest",
    description:
      "A Model Context Protocol server that provides web content fetching capabilities",
    transport: "stdio",
    permissions: {
      network: {
        outbound: {
          insecure_allow_all: true,
          allow_transport: ["tcp"],
          allow_host: ["github.com"],
          allow_port: [443],
        },
      },
    },
    tools: ["fetch"],
    env_vars: [],
    args: [],
    metadata: {
      stars: 49139,
      pulls: 6918,
      last_updated: "2025-05-27T00:20:44Z",
    },
    repository_url: "https://github.com/modelcontextprotocol/servers",
    tags: [
      "content",
      "html",
      "markdown",
      "fetch",
      "fetching",
      "get",
      "wget",
      "json",
      "curl",
      "modelcontextprotocol",
    ],
  },
  {
    name: "filesystem",
    image: "mcp/filesystem:latest",
    description:
      "Node.js server implementing Model Context Protocol (MCP) for filesystem operations.",
    transport: "stdio",
    permissions: {
      read: ["/tmp"],
      write: ["/tmp"],
      network: {
        outbound: {
          allow_transport: ["tcp"],
          allow_port: [443],
        },
      },
    },
    tools: [
      "read_file",
      "read_multiple_files",
      "write_file",
      "edit_file",
      "create_directory",
      "list_directory",
      "move_file",
      "search_files",
      "get_file_info",
      "list_allowed_directories",
    ],
    env_vars: [],
    args: [],
    metadata: {
      stars: 49139,
      pulls: 9751,
      last_updated: "2025-05-27T00:20:42Z",
    },
    repository_url: "https://github.com/modelcontextprotocol/servers",
    tags: [
      "create_directory",
      "edit_file",
      "filesystem",
      "get_file_info",
      "implementing",
      "list_allowed_directories",
      "list_directory",
      "move_file",
      "node",
      "operations",
    ],
  },
  {
    name: "firecrawl",
    image: "mcp/firecrawl:latest",
    description:
      "A powerful web scraping and content extraction MCP server that provides advanced crawling, search, and structured data extraction capabilities with LLM integration.",
    transport: "stdio",
    permissions: {
      network: {
        outbound: {
          insecure_allow_all: true,
          allow_transport: ["tcp"],
          allow_port: [443],
        },
      },
    },
    tools: [
      "firecrawl_scrape",
      "firecrawl_batch_scrape",
      "firecrawl_check_batch_status",
      "firecrawl_check_crawl_status",
      "firecrawl_search",
      "firecrawl_crawl",
      "firecrawl_extract",
      "firecrawl_deep_research",
      "firecrawl_generate_llmstxt",
      "firecrawl_map",
    ],
    env_vars: [
      {
        name: "FIRECRAWL_API_KEY",
        description: "API key for FireCrawl service authentication",
        required: true,
      },
      {
        name: "FIRECRAWL_API_URL",
        description:
          "FireCrawl API URL (default: https://api.firecrawl.dev/v1)",
        required: false,
      },
      {
        name: "FIRECRAWL_RETRY_MAX_ATTEMPTS",
        description: "Maximum number of retry attempts for API calls",
        required: false,
      },
      {
        name: "FIRECRAWL_RETRY_INITIAL_DELAY",
        description: "Initial delay in milliseconds for retry backoff",
        required: false,
      },
      {
        name: "FIRECRAWL_RETRY_MAX_DELAY",
        description: "Maximum delay in milliseconds for retry backoff",
        required: false,
      },
      {
        name: "FIRECRAWL_RETRY_BACKOFF_FACTOR",
        description: "Backoff factor for retry delay calculation",
        required: false,
      },
      {
        name: "FIRECRAWL_CREDIT_WARNING_THRESHOLD",
        description: "Credit threshold for warning notifications",
        required: false,
      },
      {
        name: "FIRECRAWL_CREDIT_CRITICAL_THRESHOLD",
        description: "Credit threshold for critical notifications",
        required: false,
      },
    ],
    args: [],
    metadata: {
      stars: 3207,
      pulls: 4360,
      last_updated: "2025-05-27T00:20:45Z",
    },
    repository_url: "https://github.com/mendableai/firecrawl-mcp-server",
    tags: [
      "web-crawler",
      "web-scraping",
      "data-collection",
      "batch-processing",
      "content-extraction",
      "search-api",
      "llm-tools",
      "javascript-rendering",
      "research",
      "automation",
    ],
  },
  {
    name: "gdrive",
    image: "mcp/gdrive:latest",
    description:
      "This MCP server integrates with Google Drive to allow listing, reading, and searching over files.",
    transport: "stdio",
    permissions: {
      network: {
        outbound: {
          allow_transport: ["tcp"],
          allow_port: [443],
        },
      },
    },
    tools: ["search"],
    env_vars: [
      {
        name: "GDRIVE_OAUTH_PATH",
        description:
          "Path to the OAuth keys file for Google Drive API authentication",
        required: true,
      },
      {
        name: "GDRIVE_CREDENTIALS_PATH",
        description: "Path to save/load Google Drive API credentials",
        required: true,
      },
    ],
    args: [],
    metadata: {
      stars: 49139,
      pulls: 4287,
      last_updated: "2025-05-27T00:20:45Z",
    },
    repository_url: "https://github.com/modelcontextprotocol/servers",
    tags: [
      "drive",
      "files",
      "gdrive",
      "google",
      "integrates",
      "listing",
      "reading",
      "searching",
      "documents",
      "spreadsheets",
      "presentations",
    ],
  },
  {
    name: "git",
    image: "mcp/git:latest",
    description:
      "A Model Context Protocol server for Git repository interaction and automation",
    transport: "stdio",
    permissions: {
      network: {
        outbound: {},
      },
    },
    tools: [
      "git_status",
      "git_diff_unstaged",
      "git_diff_staged",
      "git_diff",
      "git_commit",
      "git_add",
      "git_reset",
      "git_log",
      "git_create_branch",
      "git_checkout",
      "git_show",
      "git_init",
    ],
    env_vars: [],
    args: [],
    metadata: {
      stars: 49139,
      pulls: 4780,
      last_updated: "2025-05-27T00:20:45Z",
    },
    repository_url: "https://github.com/modelcontextprotocol/servers",
    tags: [
      "adds",
      "automation",
      "git",
      "interaction",
      "records",
      "repository",
      "shows",
      "tools",
      "unstages",
    ],
  },
  {
    name: "github",
    image: "ghcr.io/github/github-mcp-server:latest",
    description:
      "The GitHub MCP Server provides seamless integration with GitHub APIs, enabling advanced automation and interaction capabilities for developers and tools",
    transport: "stdio",
    permissions: {
      network: {
        outbound: {
          allow_transport: ["tcp"],
          allow_host: ["docs.github.com", "github.com"],
          allow_port: [443],
        },
      },
    },
    tools: [
      "get_me",
      "get_issue",
      "create_issue",
      "add_issue_comment",
      "list_issues",
      "update_issue",
      "search_issues",
      "get_pull_request",
      "list_pull_requests",
      "merge_pull_request",
      "get_pull_request_files",
      "get_pull_request_status",
      "update_pull_request_branch",
      "get_pull_request_comments",
      "get_pull_request_reviews",
      "create_pull_request_review",
      "create_pull_request",
      "create_or_update_file",
      "push_files",
      "search_repositories",
      "create_repository",
      "get_file_contents",
      "fork_repository",
      "create_branch",
      "list_commits",
      "search_code",
      "search_users",
      "get_code_scanning_alert",
      "list_code_scanning_alerts",
    ],
    env_vars: [
      {
        name: "GITHUB_PERSONAL_ACCESS_TOKEN",
        description:
          "GitHub personal access token with appropriate permissions",
        required: true,
      },
      {
        name: "GH_HOST",
        description: "GitHub Enterprise Server hostname (optional)",
        required: false,
      },
    ],
    args: [],
    metadata: {
      stars: 14342,
      pulls: 5000,
      last_updated: "2025-05-27T00:20:44Z",
    },
    repository_url: "https://github.com/github/github-mcp-server",
    tags: [
      "api",
      "create",
      "fork",
      "github",
      "list",
      "pull-request",
      "push",
      "repository",
      "search",
      "update",
      "issues",
    ],
    provenance: {
      sigstore_url: "tuf-repo-cdn.sigstore.dev",
      repository_uri: "https://github.com/github/github-mcp-server",
      repository_ref: "",
      signer_identity: "/.github/workflows/docker-publish.yml",
      runner_environment: "github-hosted",
      cert_issuer: "https://token.actions.githubusercontent.com",
    },
  },
  {
    name: "gitlab",
    image: "mcp/gitlab:latest",
    description:
      "MCP Server for the GitLab API, enabling project management, file operations, and more.",
    transport: "stdio",
    permissions: {
      network: {
        outbound: {
          allow_transport: ["tcp"],
          allow_host: ["docs.gitlab.com", "gitlab.com", "full.com"],
          allow_port: [443],
        },
      },
    },
    tools: [
      "create_or_update_file",
      "push_files",
      "search_repositories",
      "create_repository",
      "get_file_contents",
      "create_issue",
      "create_merge_request",
      "fork_repository",
      "create_branch",
    ],
    env_vars: [
      {
        name: "GITLAB_PERSONAL_ACCESS_TOKEN",
        description:
          "GitLab personal access token with appropriate permissions",
        required: true,
      },
      {
        name: "GITLAB_API_URL",
        description:
          "Base URL for GitLab API (optional, defaults to https://gitlab.com/api/v4)",
        required: false,
      },
    ],
    args: [],
    metadata: {
      stars: 49139,
      pulls: 3924,
      last_updated: "2025-05-27T00:20:43Z",
    },
    repository_url: "https://github.com/modelcontextprotocol/servers",
    tags: [
      "api",
      "create",
      "file",
      "fork",
      "gitlab",
      "management",
      "merge-request",
      "operations",
      "project",
      "search",
    ],
  },
  {
    name: "google-maps",
    image: "mcp/google-maps:latest",
    description: "MCP Server for the Google Maps API.",
    transport: "stdio",
    permissions: {
      network: {
        outbound: {
          allow_transport: ["tcp"],
          allow_host: ["developers.google.com", "maps.com"],
          allow_port: [443],
        },
      },
    },
    tools: [
      "maps_geocode",
      "maps_reverse_geocode",
      "maps_search_places",
      "maps_place_details",
      "maps_distance_matrix",
      "maps_elevation",
      "maps_directions",
    ],
    env_vars: [
      {
        name: "GOOGLE_MAPS_API_KEY",
        description: "Google Maps API key with appropriate permissions",
        required: true,
      },
    ],
    args: [],
    metadata: {
      stars: 49139,
      pulls: 3151,
      last_updated: "2025-05-27T00:20:43Z",
    },
    repository_url: "https://github.com/modelcontextprotocol/servers",
    tags: [
      "api",
      "directions",
      "distance",
      "geocode",
      "google",
      "google-maps",
      "maps",
      "places",
      "search",
    ],
  },
  {
    name: "grafana",
    image: "grafana/grafana-oss:latest",
    description:
      "A Model Context Protocol (MCP) server for Grafana OSS that provides access to your Grafana instance and the surrounding ecosystem, enabling dashboard search, datasource queries, alerting management, and incident response.",
    transport: "stdio",
    permissions: {
      network: {
        outbound: {
          allow_transport: ["tcp"],
          allow_host: ["grafana.com"],
          allow_port: [443],
        },
      },
    },
    tools: [
      "search_dashboards",
      "get_dashboard_by_uid",
      "list_datasources",
      "get_datasource_by_uid",
      "get_datasource_by_name",
      "query_prometheus",
      "list_prometheus_metric_metadata",
      "list_prometheus_metric_names",
      "list_prometheus_label_names",
      "list_prometheus_label_values",
      "list_incidents",
      "create_incident",
      "add_activity_to_incident",
      "resolve_incident",
      "query_loki_logs",
      "list_loki_label_names",
      "list_loki_label_values",
      "query_loki_stats",
      "list_alert_rules",
      "get_alert_rule_by_uid",
      "list_oncall_schedules",
      "get_oncall_shift",
      "get_current_oncall_users",
      "list_oncall_teams",
      "list_oncall_users",
    ],
    env_vars: [
      {
        name: "GRAFANA_URL",
        description: "URL of the Grafana instance to connect to",
        required: true,
      },
      {
        name: "GRAFANA_API_KEY",
        description: "Service account token with appropriate permissions",
        required: true,
      },
    ],
    args: [],
    metadata: {
      stars: 829,
      pulls: 2800,
      last_updated: "2025-05-27T00:20:43Z",
    },
    repository_url: "https://github.com/grafana/mcp-grafana",
    tags: [
      "grafana",
      "dashboards",
      "visualization",
      "monitoring",
      "alerting",
      "prometheus",
      "loki",
      "tempo",
      "pyroscope",
      "incidents",
      "observability",
      "metrics",
      "logs",
      "traces",
    ],
  },
  {
    name: "hass-mcp",
    image: "voska/hass-mcp:latest",
    description:
      "A Model Context Protocol (MCP) server for Home Assistant integration with Claude and other LLMs, enabling direct interaction with smart home devices, sensors, and automations.",
    transport: "stdio",
    permissions: {
      network: {
        outbound: {
          insecure_allow_all: true,
          allow_transport: ["tcp"],
        },
      },
    },
    tools: [
      "get_version",
      "get_entity",
      "entity_action",
      "list_entities",
      "search_entities_tool",
      "domain_summary_tool",
      "list_automations",
      "call_service_tool",
      "restart_ha",
      "get_history",
      "get_error_log",
    ],
    env_vars: [
      {
        name: "HA_URL",
        description:
          "Home Assistant instance URL (e.g. http://homeassistant.local:8123)",
        required: true,
      },
      {
        name: "HA_TOKEN",
        description: "Home Assistant Long-Lived Access Token",
        required: true,
      },
    ],
    args: [],
    metadata: {
      stars: 85,
      pulls: 5840,
      last_updated: "2025-05-27T00:20:43Z",
    },
    repository_url: "https://github.com/voska/hass-mcp",
    tags: [
      "home-assistant",
      "smart-home",
      "automation",
      "iot",
      "sensors",
      "devices",
      "control",
      "monitoring",
      "home-automation",
      "domotics",
    ],
  },
  {
    name: "k8s",
    image: "ghcr.io/stackloklabs/mkp/server:latest",
    description:
      "MKP is a Model Context Protocol (MCP) server for Kubernetes that allows LLM-powered applications to interact with Kubernetes clusters.\nIt provides tools for listing and applying Kubernetes resources through the MCP protocol.\n\nWhen running this server, you need to provide Kubernetes credentials. You can do this in several ways:\n\n1. Mount your kubeconfig file using the volume flag:\n    --volume /path/to/your/kubeconfig:/home/nonroot/.kube/config:ro\n\n2. Set the KUBECONFIG environment variable:\n    --env KUBECONFIG=/path/in/container/to/kubeconfig\n\n3. For in-cluster configuration (when running inside Kubernetes):\n    No additional configuration needed if proper service account is configured.",
    transport: "sse",
    permissions: {
      network: {
        outbound: {
          insecure_allow_all: true,
          allow_transport: ["tcp"],
          allow_port: [443],
        },
      },
    },
    tools: ["list_resources", "get_resource", "apply_resource"],
    env_vars: [
      {
        name: "KUBECONFIG",
        description:
          "Path to the kubeconfig file for Kubernetes API authentication",
        required: false,
      },
    ],
    args: [],
    metadata: {
      stars: 27,
      pulls: 4224,
      last_updated: "2025-05-27T00:20:44Z",
    },
    repository_url: "https://github.com/StacklokLabs/mkp",
    tags: [
      "kubernetes",
      "k8s",
      "api",
      "resources",
      "cluster",
      "namespaced",
      "apply",
      "get",
      "list",
    ],
    provenance: {
      sigstore_url: "tuf-repo-cdn.sigstore.dev",
      repository_uri: "https://github.com/StacklokLabs/mkp",
      repository_ref: "",
      signer_identity: "/.github/workflows/release.yml",
      runner_environment: "github-hosted",
      cert_issuer: "https://token.actions.githubusercontent.com",
    },
  },
  {
    name: "memory",
    image: "mcp/memory:latest",
    description:
      "A basic implementation of persistent memory using a local knowledge graph. This lets Claude remember information about the user across chats.",
    transport: "stdio",
    permissions: {
      network: {
        outbound: {
          allow_transport: ["tcp"],
          allow_port: [443],
        },
      },
    },
    tools: [
      "create_entities",
      "create_relations",
      "add_observations",
      "delete_entities",
      "delete_observations",
      "delete_relations",
      "read_graph",
      "search_nodes",
      "open_nodes",
    ],
    env_vars: [
      {
        name: "MEMORY_FILE_PATH",
        description:
          "Path to the memory storage JSON file (default: memory.json in the server directory)",
        required: false,
      },
    ],
    args: [],
    metadata: {
      stars: 49139,
      pulls: 7114,
      last_updated: "2025-05-27T00:20:42Z",
    },
    repository_url: "https://github.com/modelcontextprotocol/servers",
    tags: [
      "entities",
      "graph",
      "knowledge",
      "memory",
      "observations",
      "persistent",
      "relations",
    ],
  },
  {
    name: "netbird",
    image: "aantti/mcp-netbird:latest",
    description:
      "A Model Context Protocol server for NetBird, enabling management of your NetBird network.",
    transport: "sse",
    target_port: 8001,
    permissions: {
      network: {
        outbound: {
          insecure_allow_all: true,
          allow_transport: ["tcp"],
          allow_port: [443],
        },
      },
    },
    tools: [
      "list_netbird_peers",
      "list_netbird_port_allocations",
      "list_netbird_groups",
      "list_netbird_policies",
      "list_netbird_posture_checks",
      "list_netbird_networks",
      "list_netbird_nameservers",
    ],
    env_vars: [
      {
        name: "NETBIRD_API_TOKEN",
        description: "NetBird API token for authentication",
        required: true,
      },
      {
        name: "NETBIRD_HOST",
        description: "NetBird API host (default is api.netbird.io)",
        required: false,
      },
    ],
    args: ["--transport", "sse", "--sse-address", ":8001"],
    metadata: {
      stars: 31,
      pulls: 3760,
      last_updated: "2025-05-27T00:20:42Z",
    },
    repository_url: "https://github.com/aantti/mcp-netbird",
    tags: [
      "netbird",
      "vpn",
      "networking",
      "peer",
      "route",
      "dns",
      "setup-key",
      "management",
    ],
  },
  {
    name: "oci-registry",
    image: "ghcr.io/stackloklabs/ocireg-mcp/server:latest",
    description:
      "The OCI Registry MCP Server enables secure and seamless querying of OCI container registries, providing tools for image introspection, tag discovery, and manifest/config retrieval.",
    transport: "sse",
    permissions: {
      network: {
        outbound: {
          allow_transport: ["tcp"],
          allow_host: ["*"],
          allow_port: [443],
        },
      },
    },
    tools: [
      "get_image_info",
      "list_tags",
      "get_image_manifest",
      "get_image_config",
    ],
    env_vars: [
      {
        name: "OCI_TOKEN",
        description: "Bearer token for OCI registry authentication",
        required: false,
      },
      {
        name: "OCI_USERNAME",
        description: "Username for registry authentication",
        required: false,
      },
      {
        name: "OCI_PASSWORD",
        description: "Password for registry authentication",
        required: false,
      },
    ],
    args: [],
    metadata: {
      stars: 2,
      pulls: 505,
      last_updated: "2025-05-27T00:20:42Z",
    },
    repository_url: "https://github.com/StacklokLabs/ocireg-mcp",
    tags: [
      "oci",
      "registry",
      "containers",
      "images",
      "tags",
      "manifest",
      "config",
      "mcp",
      "docker",
    ],
    provenance: {
      sigstore_url: "tuf-repo-cdn.sigstore.dev",
      repository_uri: "https://github.com/StacklokLabs/ocireg-mcp",
      repository_ref: "",
      signer_identity: "/.github/workflows/release.yml",
      runner_environment: "github-hosted",
      cert_issuer: "https://token.actions.githubusercontent.com",
    },
  },
  {
    name: "osv",
    image: "ghcr.io/stackloklabs/osv-mcp/server:latest",
    description:
      "An MCP (Model Context Protocol) server that provides access to the OSV (Open Source Vulnerabilities) database. This server allows LLM-powered applications to query the OSV database for vulnerability information about packages and commits.",
    transport: "sse",
    permissions: {
      network: {
        outbound: {
          allow_transport: ["tcp"],
          allow_host: ["api.osv.dev"],
          allow_port: [443],
        },
      },
    },
    tools: [
      "query_vulnerability",
      "query_vulnerabilities_batch",
      "get_vulnerability",
    ],
    env_vars: [],
    args: [],
    metadata: {
      stars: 4,
      pulls: 3174,
      last_updated: "2025-05-27T00:20:41Z",
    },
    repository_url: "https://github.com/StacklokLabs/osv-mcp",
    tags: [
      "vulnerability",
      "security",
      "osv",
      "open-source",
      "cve",
      "packages",
      "dependencies",
      "scanning",
      "security-scanning",
      "vulnerability-detection",
    ],
    provenance: {
      sigstore_url: "tuf-repo-cdn.sigstore.dev",
      repository_uri: "https://github.com/StacklokLabs/osv-mcp",
      repository_ref: "",
      signer_identity: "/.github/workflows/release.yml",
      runner_environment: "github-hosted",
      cert_issuer: "https://token.actions.githubusercontent.com",
    },
  },
  {
    name: "perplexity-ask",
    image: "mcp/perplexity-ask:latest",
    description: "",
    transport: "stdio",
    permissions: {
      network: {
        outbound: {
          allow_transport: ["tcp"],
          allow_host: ["api.perplexity.ai"],
          allow_port: [443],
        },
      },
    },
    tools: [],
    env_vars: [
      {
        name: "PERPLEXITY_API_KEY",
        description: "Perplexity API key",
        required: true,
      },
    ],
    args: [],
    metadata: {
      stars: 49139,
      pulls: 5516,
      last_updated: "2025-05-27T00:20:44Z",
    },
    repository_url: "https://github.com/modelcontextprotocol/servers",
    tags: ["ask", "perplexity", "perplexity-ask"],
  },
  {
    name: "postgres",
    image: "mcp/postgres:latest",
    description:
      "A Model Context Protocol server that provides read-only access to PostgreSQL databases. This server enables LLMs to inspect database schemas and execute read-only queries.",
    transport: "stdio",
    permissions: {
      read: ["/tmp/db"],
      write: ["/tmp/db"],
      network: {
        outbound: {
          allow_transport: ["tcp"],
          allow_port: [443],
        },
      },
    },
    tools: ["query"],
    env_vars: [],
    args: ["postgresql://host:port/db-name"],
    metadata: {
      stars: 49139,
      pulls: 8821,
      last_updated: "2025-05-27T00:20:43Z",
    },
    repository_url: "https://github.com/modelcontextprotocol/servers",
    tags: [
      "database",
      "postgres",
      "postgresql",
      "query",
      "read-only",
      "schema",
      "sql",
    ],
  },
  {
    name: "puppeteer",
    image: "mcp/puppeteer:latest",
    description:
      "A Model Context Protocol server that provides browser automation capabilities using Puppeteer",
    transport: "stdio",
    permissions: {
      network: {
        outbound: {
          insecure_allow_all: true,
          allow_transport: ["tcp"],
          allow_port: [443],
        },
      },
    },
    tools: [
      "puppeteer_navigate",
      "puppeteer_screenshot",
      "puppeteer_click",
      "puppeteer_hover",
      "puppeteer_fill",
      "puppeteer_select",
      "puppeteer_evaluate",
    ],
    env_vars: [
      {
        name: "DOCKER_CONTAINER",
        description: "Set to true when running in Docker to use headless mode",
        required: false,
        default: "true",
      },
    ],
    args: [],
    metadata: {
      stars: 49139,
      pulls: 12435,
      last_updated: "2025-05-27T00:20:45Z",
    },
    repository_url: "https://github.com/modelcontextprotocol/servers",
    tags: [
      "automation",
      "browser",
      "capabilities",
      "navigate",
      "provides",
      "puppeteer",
      "puppeteer_click",
      "puppeteer_evaluate",
      "puppeteer_fill",
      "puppeteer_hover",
    ],
  },
  {
    name: "pushover",
    image: "ashiknesin/pushover-mcp:latest",
    description:
      "A Model Context Protocol implementation for sending notifications via Pushover.net, enabling AI agents to send customizable push notifications to devices.",
    transport: "stdio",
    permissions: {
      network: {
        outbound: {
          allow_transport: ["tcp"],
          allow_host: ["api.pushover.net"],
          allow_port: [443],
        },
      },
    },
    tools: ["send"],
    env_vars: [
      {
        name: "PUSHOVER_TOKEN",
        description: "Application token from Pushover.net",
        required: true,
      },
      {
        name: "PUSHOVER_USER",
        description: "User key from Pushover.net",
        required: true,
      },
    ],
    args: [],
    metadata: {
      stars: 18,
      pulls: 5680,
      last_updated: "2025-05-27T00:20:42Z",
    },
    repository_url: "https://github.com/ashiknesin/pushover-mcp",
    tags: [
      "notifications",
      "push-notifications",
      "pushover",
      "alerts",
      "messaging",
      "mobile",
      "devices",
      "communication",
      "real-time",
      "monitoring",
    ],
  },
  {
    name: "redis",
    image: "mcp/redis:latest",
    description:
      "A Model Context Protocol server that provides access to Redis databases. This server enables LLMs to interact with Redis key-value stores through a set of standardized tools.",
    transport: "stdio",
    permissions: {
      network: {
        outbound: {
          allow_transport: ["tcp"],
          allow_port: [443, 6379],
        },
      },
    },
    tools: ["set", "get", "delete", "list"],
    env_vars: [],
    args: [],
    metadata: {
      stars: 49139,
      pulls: 3821,
      last_updated: "2025-05-27T00:20:45Z",
    },
    repository_url: "https://github.com/modelcontextprotocol/servers",
    tags: ["redis", "database", "key-value", "storage", "cache", "data"],
  },
  {
    name: "semgrep",
    image: "ghcr.io/semgrep/mcp:latest",
    description:
      "An MCP server for using Semgrep to scan code for security vulnerabilities. Semgrep is a fast, deterministic static analysis tool that semantically understands many languages and comes with over 5,000 rules.",
    transport: "sse",
    permissions: {
      network: {
        outbound: {
          allow_transport: ["tcp"],
          allow_host: ["semgrep.dev", "semgrep.com"],
          allow_port: [443],
        },
      },
    },
    tools: [
      "security_check",
      "semgrep_scan",
      "semgrep_scan_with_custom_rule",
      "get_abstract_syntax_tree",
      "supported_languages",
      "semgrep_rule_schema",
      "write_custom_semgrep_rule",
    ],
    env_vars: [
      {
        name: "SEMGREP_APP_TOKEN",
        description: "Token for connecting to Semgrep AppSec Platform",
        required: false,
      },
    ],
    args: [],
    metadata: {
      stars: 160,
      pulls: 4200,
      last_updated: "2025-05-27T00:20:41Z",
    },
    repository_url: "https://github.com/semgrep/mcp",
    tags: [
      "security",
      "static-analysis",
      "code-scanning",
      "vulnerability-detection",
      "sast",
      "code-quality",
      "security-scanning",
      "semgrep",
      "ast",
      "code-analysis",
    ],
  },
  {
    name: "sentry",
    image: "mcp/sentry:latest",
    description:
      "A Model Context Protocol server for retrieving and analyzing issues from Sentry.io",
    transport: "stdio",
    permissions: {
      network: {
        outbound: {
          allow_transport: ["tcp"],
          allow_port: [443],
        },
      },
    },
    tools: ["get_sentry_issue"],
    env_vars: [
      {
        name: "SENTRY_TOKEN",
        description: "Sentry authentication token for API access",
        required: true,
      },
    ],
    args: [],
    metadata: {
      stars: 49139,
      pulls: 5462,
      last_updated: "2025-05-27T00:20:45Z",
    },
    repository_url: "https://github.com/modelcontextprotocol/servers",
    tags: ["analyzing", "issues", "retrieving", "sentry", "tools"],
  },
  {
    name: "sequentialthinking",
    image: "mcp/sequentialthinking:latest",
    description:
      "MCP server enabling dynamic problem-solving with a structured, reflective approach that can adapt and evolve as understanding deepens.",
    transport: "stdio",
    permissions: {
      network: {
        outbound: {
          allow_transport: ["tcp"],
          allow_port: [443],
        },
      },
    },
    tools: ["sequentialthinking"],
    env_vars: [],
    args: [],
    metadata: {
      stars: 49139,
      pulls: 7751,
      last_updated: "2025-05-27T00:20:43Z",
    },
    repository_url: "https://github.com/modelcontextprotocol/servers",
    tags: [
      "approach",
      "dynamic",
      "enabling",
      "problem",
      "reflective",
      "sequentialthinking",
      "solving",
      "structured",
      "step-by-step",
      "revision",
      "branching",
      "chain-of-thought",
    ],
  },
  {
    name: "slack",
    image: "mcp/slack:latest",
    description:
      "MCP Server for the Slack API, enabling Claude to interact with Slack workspaces",
    transport: "stdio",
    permissions: {
      network: {
        outbound: {
          allow_transport: ["tcp"],
          allow_host: ["api.slack.com", "slack.com"],
          allow_port: [443],
        },
      },
    },
    tools: [
      "slack_list_channels",
      "slack_post_message",
      "slack_reply_to_thread",
      "slack_add_reaction",
      "slack_get_channel_history",
      "slack_get_thread_replies",
      "slack_get_users",
      "slack_get_user_profile",
    ],
    env_vars: [
      {
        name: "SLACK_BOT_TOKEN",
        description: "Bot User OAuth Token that starts with xoxb-",
        required: true,
      },
      {
        name: "SLACK_TEAM_ID",
        description: "Slack Team ID that starts with T",
        required: true,
      },
    ],
    args: [],
    metadata: {
      stars: 49139,
      pulls: 3667,
      last_updated: "2025-05-27T00:20:42Z",
    },
    repository_url: "https://github.com/modelcontextprotocol/servers",
    tags: [
      "api",
      "claude",
      "enabling",
      "interact",
      "list",
      "post",
      "reply",
      "slack",
      "tools",
      "workspaces",
    ],
  },
  {
    name: "sqlite",
    image: "mcp/sqlite:latest",
    description:
      "MCP server with SQLite for SQL queries, data analysis, and auto-generated business insights.\n\n\n\n\n",
    transport: "stdio",
    permissions: {
      network: {
        outbound: {
          allow_transport: ["tcp"],
          allow_port: [443],
        },
      },
    },
    tools: [
      "read_query",
      "write_query",
      "create_table",
      "list_tables",
      "describe_table",
      "append_insight",
    ],
    env_vars: [],
    args: [],
    metadata: {
      stars: 49139,
      pulls: 6414,
      last_updated: "2025-05-27T00:20:43Z",
    },
    repository_url: "https://github.com/modelcontextprotocol/servers",
    tags: [
      "analysis",
      "auto",
      "business",
      "data",
      "generated",
      "insights",
      "queries",
      "sql",
      "sqlite",
      "tools",
    ],
  },
  {
    name: "time",
    image: "mcp/time:latest",
    description:
      "MCP server for time info and IANA timezone conversions with auto system timezone detection.\n\n\n\n\n",
    transport: "stdio",
    permissions: {
      network: {
        outbound: {
          allow_transport: ["tcp"],
          allow_port: [443],
        },
      },
    },
    tools: ["get_current_time", "convert_time"],
    env_vars: [],
    args: [],
    metadata: {
      stars: 49139,
      pulls: 4830,
      last_updated: "2025-05-27T00:20:44Z",
    },
    repository_url: "https://github.com/modelcontextprotocol/servers",
    tags: [
      "auto",
      "available",
      "configuration",
      "conversions",
      "convert_time",
      "customization",
      "details",
      "detection",
      "example",
      "examples",
    ],
  },
];
