export const MCP_OPTIMIZER_GROUP_NAME = '__mcp-optimizer__'
export const META_MCP_SERVER_NAME = 'internal---meta-mcp'
export const META_MCP_REGISTRY_SERVER_NAME = 'meta-mcp'
export const META_MCP_IMAGE = 'ghcr.io/toolhive/meta-mcp:latest'
export const ALLOWED_GROUPS_ENV_VAR = 'ALLOWED_GROUPS'
