export const MCP_OPTIMIZER_GROUP_NAME = '__mcp-optimizer__'
export const META_MCP_SERVER_NAME = 'toolhive-mcp-optimizer'
export const ALLOWED_GROUPS_ENV_VAR = 'ALLOWED_GROUPS'
export const MCP_OPTIMIZER_REGISTRY_SERVER_NAME = 'mcp-optimizer'
export const DEPRECATED_MCP_OPTIMIZER_REGISTRY_SERVER_NAME = 'meta-mcp'
