name: 'Setup Windows Code Signing'
description: 'Sets up DigiCert KeyLocker for Windows code signing'

inputs:
  sm-host:
    description: 'DigiCert SigningManager host'
    required: true
  sm-api-key:
    description: 'DigiCert SigningManager API key'
    required: true
  sm-client-cert-file-b64:
    description: 'Base64 encoded client certificate file'
    required: true
  sm-client-cert-password:
    description: 'Client certificate password'
    required: true
  sm-code-signing-cert-sha1-hash:
    description: 'SHA1 hash of the code signing certificate'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup DigiCert KeyLocker
      if: runner.os == 'Windows'
      shell: bash
      env:
        SM_HOST: ${{ inputs.sm-host }}
        SM_API_KEY: ${{ inputs.sm-api-key }}
        SM_CLIENT_CERT_FILE_B64: ${{ inputs.sm-client-cert-file-b64 }}
        SM_CLIENT_CERT_PASSWORD: ${{ inputs.sm-client-cert-password }}
        SM_CODE_SIGNING_CERT_SHA1_HASH: ${{ inputs.sm-code-signing-cert-sha1-hash }}
      run: |
        # Setup certificate
        echo "$SM_CLIENT_CERT_FILE_B64" | base64 --decode > /d/Certificate_pkcs12.p12

        # Set environment variables
        echo "SM_HOST=$SM_HOST" >> "$GITHUB_ENV"
        echo "SM_API_KEY=$SM_API_KEY" >> "$GITHUB_ENV"
        echo "SM_CLIENT_CERT_FILE=D:\\Certificate_pkcs12.p12" >> "$GITHUB_ENV"
        echo "SM_CLIENT_CERT_PASSWORD=$SM_CLIENT_CERT_PASSWORD" >> "$GITHUB_ENV"
        echo "SM_CODE_SIGNING_CERT_SHA1_HASH=$SM_CODE_SIGNING_CERT_SHA1_HASH" >> "$GITHUB_ENV"

        # Add Windows SDK tools to PATH for signtool
        echo "C:\Program Files (x86)\Windows Kits\10\App Certification Kit" >> $GITHUB_PATH
        echo "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools" >> $GITHUB_PATH

        # Download and install DigiCert KeyLocker tools
        curl -X GET https://one.digicert.com/signingmanager/api-ui/v1/releases/Keylockertools-windows-x64.msi/download -H "x-api-key:$SM_API_KEY" -o Keylockertools-windows-x64.msi
        msiexec /i Keylockertools-windows-x64.msi /quiet /qn

        # Register the KSP
        smksp_registrar.exe register

        # Synchronize certificates
        smksp_cert_sync.exe
