name: Lint PR title
on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize
jobs:
  lint-pr-title:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - uses: ./.github/actions/setup

      - name: Install commitlint
        run: |
          pnpm i -D -w commitlint @commitlint/config-conventional

      - name: Validate PR title
        run: echo "${{ github.event.pull_request.title }}" | pnpm dlx commitlint -x '@commitlint/config-conventional'
