name: On Merge to main
on:
  push:
    branches:
      - main
permissions: write-all
jobs:
  security:
    name: Security Checks
    uses: ./.github/workflows/_security-checks.yml

  static-checks:
    name: Static Checks
    uses: ./.github/workflows/_static-checks.yml
    secrets: inherit

  unit-tests:
    name: Unit Tests
    uses: ./.github/workflows/_unit-tests.yml
    secrets: inherit

  # The e2e tests are currently flaky, so we're disabling them for now, needs to be investigated
  # e2e-tests:
  #   name: End-to-end tests
  #   uses: ./.github/workflows/_e2e.yml
  #   secrets: inherit
