name: On PR
permissions: write-all
on:
  pull_request:
jobs:
  security:
    name: Security Checks
    uses: ./.github/workflows/_security-checks.yml

  static-checks:
    name: Static Checks
    uses: ./.github/workflows/_static-checks.yml
    secrets: inherit

  build-matrix:
    name: Build Matrix
    uses: ./.github/workflows/_build-matrix.yml
    secrets: inherit

  unit-tests:
    name: Unit Tests
    uses: ./.github/workflows/_unit-tests.yml
    secrets: inherit

  e2e-tests-ubuntu:
    name: End-to-end tests
    uses: ./.github/workflows/_e2e-ubuntu.yml
    secrets: inherit

  e2e-tests-mac:
    name: End-to-end tests
    uses: ./.github/workflows/_e2e-mac.yml
    secrets: inherit
